name: CI/CD - Build, Push, and Deploy Docker Image
run-name: "CI/CD"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker and Login
        id: docker-setup
        uses: ./.github/actions/docker-setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.docker-setup.outputs.docker_image }}:latest
            ghcr.io/${{ steps.docker-setup.outputs.docker_image }}:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker and Login
        id: docker-setup
        uses: ./.github/actions/docker-setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/kevin/projects/parker

            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker stop parker && docker rm parker
            docker pull ghcr.io/${{ steps.docker-setup.outputs.docker_image }}:latest

            docker run -d \
            --name parker \
            -e FLARESOLVER_ENDPOINT="http://${{ secrets.REMOTE_HOST }}:8191/v1" \
            -e NOTIFICATION_ENDPOINT="http://${{ secrets.REMOTE_HOST }}:8080" \
            -v $(pwd)/jobs.db:/app/jobs.db \
            ghcr.io/${{ steps.docker-setup.outputs.docker_image }}:latest
