name: CI/CD - Build, Push, and Deploy Docker Image
run-name: "CI/CD"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker
        uses: ./.github/actions/docker-setup.yml

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ env.DOCKER_IMAGE }}:latest
            ghcr.io/${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup Docker
        uses: ./.github/actions/docker-setup.yml

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/kevin/projects/parker
            docker pull ghcr.io/${{ env.DOCKER_IMAGE }}:latest

            docker run -d \
              -v $(pwd)/jobs.db:/app/jobs.db \
              ghcr.io/${{ env.DOCKER_IMAGE }}:latest
